###################################################################
#                                                                 #
#          ConsoleCommands Config / ConsoleCommands 配置          #
#                       By ImCur / Man297                         #
#     Github: https://github.com/MessyCraft/ConsoleCommands/      #
#                                                                 #
###################################################################

###################################################################
#                                                                 #
#                     Basic config / 基础配置                      #
#                                                                 #
###################################################################

# The maximum limit of /loopcmd can provide(-1 to disable limit, 0 or make it empty to disable this function)
# (Some command takes a lot of performance impact - do not assume your server can hold that!)
# /loopcmd 所能提供的最高循环次数 设为-1表示不限制 留空或设为0表示禁用
# (某些命令占用巨大,不要过于高估服务器性能)
times_limit: 100


###################################################################
#                                                                 #
#                   Security config / 安全设置                     #
#                                                                 #
###################################################################

# Whether allow this plugin to execute LuckPerms command as console or player
# If allowed, player has ConsoleCommands permission can access LuckPerms to get permission for all Bungeecord server!
# if your server is not Bungeecord server or don't have LuckPerms, you can ignore this config.
# 是否允许本插件以控制台/玩家的身份执行 LuckPerms 命令 默认禁止
# 有可能获得整个 BungeeCord 群组服的权限 没有 Bungeecord 或没有 LuckPerms 的服务器请忽视
allow_lp_command: false
