name: ConsoleCommands
authors: [ ImCur_ , Man297 ]
description: A minecraft bukkit plugin allows you to execute commands as player or server console.
main: com.github.messycraft.consolecommands.ConsoleCommands
version: 1.2
softdepend: [ LuckPerms ]
api-version: 1.13

commands:
  executeconsole:
    description: Execute commands as console
    aliases: [execc,console]
  executeplayer:
    description: Execute commands as player
    aliases: [execp,fsudo]
  loopcmd:
    description: Loop commands
  ccreload:
    description: Reload config
    permission: consolecommands.reload

permissions:
  consolecommands.help:
    description: Open plugin help
    default: true
  consolecommands.version:
    description: Check version information
    default: true
  consolecommands.loopcmd:
    description: Allow to loop commands
    default: op
  consolecommands.execute.console:
    description: Allow to execute commands as console
    default: op
  consolecommands.execute.player:
    description: Allow to execute commands as player
    default: op
  consolecommands.reload:
    description: Allow to reload config.yml
    default: op

